name = "The Goofy Pack"
author = "Figura Goofballs"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5469f853c0c6abb8836a9e4a2eee234a3ff7f5ebb77a68e9ef32c2b5b8c365e9"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
