name = "The Goofy Pack"
author = "Figura Goofballs"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e8f2ca3f86394e14f4731005bdeabe90f8be0f1865eabc4aceaad551af511ce"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
