name = "The Goofy Pack"
author = "Figura Goofballs"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03dc4f9ee32183c810bf292e9d2de1c3e81cb37f076b5933c8484caf960cba00"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
